services:
  flask:
    build:
      context: .
      dockerfile: Dockerfile.flask
    container_name: flask_api
    ports:
      - "5000:5000"   # Run Flask on 5000
    environment:
      - FLASK_PORT=5000
    networks:
      - projectnet

  node:
    build:
      context: .
      dockerfile: Dockerfile.node
    container_name: node_server
    ports:
      - "8000:8000"
    environment:
      - FLASK_PREDICT_URL=http://flask:5000/predict
      - MONGO_URI=mongodb+srv://karthik3116k:SDTo3NAOVYvHakrm@cluster0.edbxe4c.mongodb.net/temp?retryWrites=true&w=majority&appName=Cluster0
    depends_on:
      - flask
    networks:
      - projectnet

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: react_frontend
    ports:
      - "3000:80"
    depends_on:
      - node
    networks:
      - projectnet

networks:
  projectnet:
    driver: bridge
